//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Rate : IEquatable<Rate>
    {

        public int Id { get; set; }
        public int EmployeeId { get; set; }

        public double Value { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual Employee Employee { get; set; }

        public virtual DateTime TimeOfCommit { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rate()
        {
            
        }

        public Rate(double value) : this()
        {
            Value = value;
        }

        public bool Equals(Rate other)
        {
            return Value == other.Value;
        }
    }
}
